services:
  users:
    build: ./UsersService
    image: microday3/users:dev
    container_name: users-svc
    ports: ["5001:8080"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks: [ msnet ]
    # موقتاً healthcheck را حذف/کامنت کن (پایین توضیح دادم چرا)

  products:
    build: ./ProductsService
    image: microday3/products:dev
    container_name: products-svc
    ports: ["5002:8080"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks: [ msnet ]

  orders:
    build: ./OrdersService
    image: microday3/orders:dev
    container_name: orders-svc
    ports: ["5003:8080"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks: [ msnet ]
    depends_on:
      users:
        condition: service_started
      products:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    pull_policy: never   # مهم: اصلاً سعی نکنه از Docker Hub بکشه
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [ msnet ]

networks:
  msnet:
    driver: bridge
